/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SegmentRouteImport } from './routes/segment'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as OtaRouteImport } from './routes/ota'
import { Route as OccupancyRouteImport } from './routes/occupancy'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as CompsetRouteImport } from './routes/compset'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyLkSimpangLimaRouteImport } from './routes/property.lk-simpang-lima'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentRoute = SegmentRouteImport.update({
  id: '/segment',
  path: '/segment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaRoute = OtaRouteImport.update({
  id: '/ota',
  path: '/ota',
  getParentRoute: () => rootRouteImport,
} as any)
const OccupancyRoute = OccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const CompsetRoute = CompsetRouteImport.update({
  id: '/compset',
  path: '/compset',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyLkSimpangLimaRoute = PropertyLkSimpangLimaRouteImport.update({
  id: '/property/lk-simpang-lima',
  path: '/property/lk-simpang-lima',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compset': typeof CompsetRoute
  '/engineering': typeof EngineeringRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/hr': typeof HrRoute
  '/ingestion': typeof IngestionRoute
  '/occupancy': typeof OccupancyRoute
  '/ota': typeof OtaRoute
  '/reviews': typeof ReviewsRoute
  '/segment': typeof SegmentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/property/lk-simpang-lima': typeof PropertyLkSimpangLimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compset': typeof CompsetRoute
  '/engineering': typeof EngineeringRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/hr': typeof HrRoute
  '/ingestion': typeof IngestionRoute
  '/occupancy': typeof OccupancyRoute
  '/ota': typeof OtaRoute
  '/reviews': typeof ReviewsRoute
  '/segment': typeof SegmentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/property/lk-simpang-lima': typeof PropertyLkSimpangLimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compset': typeof CompsetRoute
  '/engineering': typeof EngineeringRoute
  '/esg': typeof EsgRoute
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/hr': typeof HrRoute
  '/ingestion': typeof IngestionRoute
  '/occupancy': typeof OccupancyRoute
  '/ota': typeof OtaRoute
  '/reviews': typeof ReviewsRoute
  '/segment': typeof SegmentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/property/lk-simpang-lima': typeof PropertyLkSimpangLimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/compset'
    | '/engineering'
    | '/esg'
    | '/events'
    | '/finance'
    | '/forecast'
    | '/hr'
    | '/ingestion'
    | '/occupancy'
    | '/ota'
    | '/reviews'
    | '/segment'
    | '/settings'
    | '/social'
    | '/property/lk-simpang-lima'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/compset'
    | '/engineering'
    | '/esg'
    | '/events'
    | '/finance'
    | '/forecast'
    | '/hr'
    | '/ingestion'
    | '/occupancy'
    | '/ota'
    | '/reviews'
    | '/segment'
    | '/settings'
    | '/social'
    | '/property/lk-simpang-lima'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/compset'
    | '/engineering'
    | '/esg'
    | '/events'
    | '/finance'
    | '/forecast'
    | '/hr'
    | '/ingestion'
    | '/occupancy'
    | '/ota'
    | '/reviews'
    | '/segment'
    | '/settings'
    | '/social'
    | '/property/lk-simpang-lima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CompsetRoute: typeof CompsetRoute
  EngineeringRoute: typeof EngineeringRoute
  EsgRoute: typeof EsgRoute
  EventsRoute: typeof EventsRoute
  FinanceRoute: typeof FinanceRoute
  ForecastRoute: typeof ForecastRoute
  HrRoute: typeof HrRoute
  IngestionRoute: typeof IngestionRoute
  OccupancyRoute: typeof OccupancyRoute
  OtaRoute: typeof OtaRoute
  ReviewsRoute: typeof ReviewsRoute
  SegmentRoute: typeof SegmentRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  PropertyLkSimpangLimaRoute: typeof PropertyLkSimpangLimaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segment': {
      id: '/segment'
      path: '/segment'
      fullPath: '/segment'
      preLoaderRoute: typeof SegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota': {
      id: '/ota'
      path: '/ota'
      fullPath: '/ota'
      preLoaderRoute: typeof OtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occupancy': {
      id: '/occupancy'
      path: '/occupancy'
      fullPath: '/occupancy'
      preLoaderRoute: typeof OccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compset': {
      id: '/compset'
      path: '/compset'
      fullPath: '/compset'
      preLoaderRoute: typeof CompsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/lk-simpang-lima': {
      id: '/property/lk-simpang-lima'
      path: '/property/lk-simpang-lima'
      fullPath: '/property/lk-simpang-lima'
      preLoaderRoute: typeof PropertyLkSimpangLimaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CompsetRoute: CompsetRoute,
  EngineeringRoute: EngineeringRoute,
  EsgRoute: EsgRoute,
  EventsRoute: EventsRoute,
  FinanceRoute: FinanceRoute,
  ForecastRoute: ForecastRoute,
  HrRoute: HrRoute,
  IngestionRoute: IngestionRoute,
  OccupancyRoute: OccupancyRoute,
  OtaRoute: OtaRoute,
  ReviewsRoute: ReviewsRoute,
  SegmentRoute: SegmentRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  PropertyLkSimpangLimaRoute: PropertyLkSimpangLimaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
